### PR TITLE
Update Ktor 3.0.0

### PR DESCRIPTION
**Pull request by sonatard**

### CODE REVIEW

**Comment by sonatard** [comment]
@BoD @martinbonnin I tried updating to Ktor 3, but I encountered the following error that I couldn't resolve. It might be related to the version of the dependency packages, but could you help me with this?

```
> Task :apollo-engine-ktor:linkDebugTestIosSimulatorArm64
e: Compilation failed: IrTypeAliasPublicSymbolImpl for io.ktor.utils.io.core/ByteReadPacket|null[0] is already bound: TYPEALIAS name:ByteReadPacket visibility:public expandedType:kotlinx.io.Source

 * Source files: 
 * Compiler version: 2.0.0
 * Output kind: PROGRAM

e: java.lang.IllegalStateException: IrTypeAliasPublicSymbolImpl for io.ktor.utils.io.core/ByteReadPacket|null[0] is already bound: TYPEALIAS name:ByteReadPacket visibility:public expandedType:kotlinx.io.Source
	at org.jetbrains.kotlin.ir.symbols.impl.IrBindablePublicSymbolBase.bind(IrPublicSymbolBase.kt:69)
	at org.jetbrains.kotlin.ir.declarations.impl.IrTypeAliasImpl.<init>(IrTypeAliasImpl.kt:45)
	at org.jetbrains.kotlin.ir.declarations.impl.AbstractIrFactoryImpl.createTypeAlias(IrFactoryImpl.kt:358)
	at 
```

**Comment by martinbonnin** [comment]
@sonatard my hunch is that the Ktor version in `apollo-kotlin` is conflicting with the one in `apollo-kotlin-ktor-support`. Can you try updating Ktor [here](https://github.com/apollographql/apollo-kotlin/blob/main/gradle/libraries.toml#L37) first?

**Comment by martinbonnin** [comment]
I was going to comment here but you were faster than me :)! From the tests I did, I think you'll also need to update Kotlin to 2.0.21

**Comment by martinbonnin** [comment]
(and also wait for the artifacts to be propagated on maven central, I just hit release and it takes 5-180min for Sonatype to move all the files accross the CDN)

**Comment by martinbonnin** [comment]
All good, it's out now https://central.sonatype.com/namespace/com.apollographql.apollo

**Comment by sonatard** [comment]
@martinbonnin I don't have sufficient knowledge related to KMP. It seems it was too early for me to take on this challenge 😢

**Comment by martinbonnin** [comment]
@sonatard there are a lot of moving parts but I think you're almost there! Can you try bumping the Kotlin version to 2.0.21 [here](https://github.com/apollographql/apollo-kotlin-ktor-support/blob/main/build.gradle.kts#L4)?

It looks like the 2.0.0 compiler is not happy with the 2.0.21 JS artifacts from Apollo Kotlin

**Review by martinbonnin — APPROVED** [review]
All good! ✅ 
Is it ready to merge or did you want to add more commits?

**Comment by sonatard** [comment]
Thanks to your comment, I was able to resolve the issue successfully! 

> Is it ready to merge or did you want to add more commits?
There are no further commits.

**Comment by martinbonnin** [comment]
Thanks for the contribution 💙I'll do a release just following this.

**Pull request merged**
